payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /

administration:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /

chambre:
    resource: "@ChambreBundle/Resources/config/routing.yml"
    prefix:   /

client:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
