services:
#    client.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    UserBundle\Controller\DefaultController:
      autowire: true # or define your controller constructor and configure its arguments explicitly
      tags: [ 'controller.service_arguments' ]