reservation_reservation:
    resource: "@ReservationBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

add_reservation:
    path: /
    defaults: { _controller: ReservationBundle:Reservation:addReservation}
apropos_page:
    path: /apropos
    defaults: { _controller: ReservationBundle:Reservation:apropos}

show_facture:
    path: /facture
    defaults: { _controller: ReservationBundle:Reservation:facturer}

action_facture:
    path: /facture/{id}/{action}
    defaults: { _controller: ReservationBundle:Reservation:facturer}
list_reservation:
    path: /listReservation
    defaults: { _controller: ReservationBundle:Reservation:index}